### ISSUE TITLE
[Feature] Documentation on how to use the library

### ISSUE THREAD

**Issue by RobinLanglois** [TinkoffCreditSystems/uconfig#5]
Hello and thank you for your work.

**Is your feature request related to a problem? Please describe.**
I'm struggling to understand how to include the library in my project and how to use it properly. At the moment, my project doesn't want to compile because of `#include <uconfig/Interface.h>` in `Interface.h`. It can't find `<uconfig>` and ask me to replace with quotes, so I must have forgotten something to do.

**Describe the solution you'd like**
I am not so experienced with C++ at the moment, so maybe it's only me who's bad. But I would find convenient to have a couple of lines in the README to explain how to use this library.

Regards

**Comment by i-vovk** [comment]
Thanks for the issue.
Generally, to use any code/lib you need to tell your compiler where to lookup for its' headers and/or libraries. For gcc/clang it can be done via `-I` and `-l` flags. Any particular situation depends on what you are using to build your project. 
Very common scenarios would be:

1. You are invoking compiler manually. To use header-only lib (uconfig case) you need to pass `-I<path to uconfig include folder>`. Meaning, if you cloned it into `~/uconfig/`, then use `-I~/uconfig/include`.
2. Or you can install uconfig onto your system via `cmake -H. -Bbuild && cd build/ && make install` (sudo may be required). This will put lib headers into the system's default folder, so you don't need to pass an extra `-I` manually.
3. Or, if you are using cmake to build your project, you can use **installed uconfig** with [`find_package(uconfig REQUIRED)`](https://cmake.org/cmake/help/latest/command/find_package.html) then [`target_link_libraries(<your target> uconfig::uconfig)`](https://cmake.org/cmake/help/latest/command/target_link_libraries.html). Alternatively, you can **include uconfig** with [add_subdirectory](https://cmake.org/cmake/help/latest/command/add_subdirectory.html)/[ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html)/[FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) and then use it. 

If you are cmake guy, then this may be helpful - https://cliutils.gitlab.io/modern-cmake/. I'll add more info to the README, thank you.

**Comment by i-vovk** [comment]
Also, there is a conan-package available – https://conan.io/center/tcsbank-uconfig
On how-to-use Conan – https://docs.conan.io/en/latest/

**Comment by RobinLanglois** [comment]
Thank you for your answer, it seemed to work. Sorry, I really forgot to tell that I was using CMake, but you answered it anyway.
Feel free to close when you want.
Regards
